# -*- coding: utf-8 -*-
"""Euler Problems

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12gF6j6yk1Z-X1HS7ad6o1tq6le_cA6Vm

#Multiples of 3 and 5
##Problem 1 
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.
"""

import numpy as np
 #creating empty lists to use
 fives = [] 
 threes = []
 other = []
 #transcribing all relevent numbers
 for i in range(1,1000):
   if i%3==0:
     threes.append(i)
   elif i%5==0:
     fives.append(i)
   else:
     other.append(i)
#print (fives, threes, other) - checking lists
#math:
total = 0
for ele in range(0, len(fives)):
  total = total + fives[ele]

for ele in range(0, len(threes)):
  total = total + threes[ele]

print(total)